### ISSUE TITLE
PM2 not working (Orange Pi 3 LTS + Ubuntu 20)

### ISSUE THREAD

**Issue by paulohlcosta** [ShinobiCCTV/Shinobi-Installer#2]
> Platform = Orange Pi 3 LTS (Allwinner H6, 2GB RAM)
> OS = Ubuntu 20 (Linux Kernel 5.10)
> Linux 5.10.75-sun50iw6
> node v16.15.0
> npm  v8.11.0

Hello,
I successfully had installed Shinobi via Ninja method on this SBC and ran for the first time, without rebooting. The dashboard and superuser pages were accessible, I got cameras working and so on.

Problems appeared when I rebooted, PM2 were unable to start over.
I tried reinstalling PM2, but got problems with "EINTEGRITY";
I tried reinstalling Shinobi via Ubuntu : The Easier Way, and noticed the following:

```
Shinobi - Install PM2
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/optionator: sha512-6BJk6d+eR5DGlJ7JELjRbaSmvpJfofH4MHK5P5L+hI1P6CEUKCfGcAvLl6VmU4bFcB84eG5zDoW7J+9Q5hh1Mw== integrity checksum failed when using sha512: wanted sha512-6BJk6d+eR5DGlJ7JELjRbaSmvpJfofH4MHK5P5L+hI1P6CEUKCfGcAvLl6VmU4bFcB84eG5zDoW7J+9Q5hh1Mw== but got sha512-2KUFPW2yApB9aYu9qgwzCxXHcsLEWil7+6bBUrAwcVmLk2ctZOhBKsadNKDusGdx1FzU98D0NBWYr+ApCEg6qQ==. (11207 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-26T13_42_41_108Z-debug-0.log
Shinobi - Finished
```

and later:

```

Shinobi - Start Shinobi and set to start on boot?
(y)es or (N)o
y
sudo: pm2: command not found
sudo: pm2: command not found
sudo: pm2: command not found
sudo: pm2: command not found
sudo: pm2: command not found
=====================================
||=====   Install Completed   =====||
=====================================
```

Can this be solved by manually installing PM2?
Is there any other way to start Shinobi?

**Comment by moeiscool** [comment]
See this repo instead https://gitlab.com/Shinobi-Systems/Shinobi-Installer

**Comment by paulohlcosta** [comment]
Solved by Updating Ubuntu to version 22 (Linux kernel 5.16) available at OrangePi website.
