### ISSUE TITLE
node-pre-gyp - Ubuntu-touchless install

### ISSUE THREAD

**Issue by bzaks1424** [ShinobiCCTV/Shinobi-Installer#3]
Hey team - had a bit of a fun night debugging and going through the ubuntu-touchless install on Ubuntu 22.04

Just out of curiosity - why aren't we using the npm install of this?
I ended up having to replace the` apt install node-pre-gyp` with `npm install node-pre-gyp -g`

I love writing shell scripts - would love to contribute if you want me to take a look at anything and change any of the scripts.

**Comment by moeiscool** [comment]
Please see the gitlab repo https://gitlab.com/Shinobi-Systems/Shinobi-installer
we would love your contributions :) come by the community chat if you want to dev chat with us :D https://shinobi.community
